[workspace]
members = [
    "ci/casper_updater",
    "execution_engine",
    "execution_engine_testing/test_support",
    "execution_engine_testing/tests",
    "hashing",
    "json_rpc",
    "node",
    "smart_contracts/contract",
    "smart_contracts/contracts/[!.]*/*",
    "types",
    "utils/global-state-update-gen",
    "utils/validation",
    "utils/highway-rewards-analysis",
]
# Ensures we do not pull in all the features of dev dependencies when building.
resolver = "2"

default-members = [
    "ci/casper_updater",
    "execution_engine",
    "execution_engine_testing/test_support",
    "execution_engine_testing/tests",
    "hashing",
    "json_rpc",
    "node",
    "types",
    "utils/global-state-update-gen",
    "utils/validation",
    "utils/highway-rewards-analysis",
]

exclude = ["utils/nctl/remotes/casper-client-rs"]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
