name: Casper Security Submission Form
description: Please submit your report using the form below. 
title: '[Casper Security] Submission'
labels:
  - casper-security
body:
  - type: markdown
    attributes:
      value: |
        This is a submission form for Casper security issues.
  - type: input
    id: email
    attributes:
      label: Your email address
      placeholder: john@doe.com
    validations:
      required: true
  - type: input
    id: other-contact
    attributes:
      label: Any other way to get in touch with you? (any form of communication channel)
    validations:
      required: false
  - type: textarea
    id: desc-issue
    attributes:
      label: Description
      placeholder: Please describe the issue here.
      description: Please provide a detailed description of the issue. Add as much detail as possible. 
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      placeholder: Please describe how to reproduce the issue here.
      description: Describe how to reproduce the issue, with as much detail as possible. 
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional)
      description: Please attach any logs, screenshots, or links that may help with the analysis.
    validations:
      required: false